project_id = "rrsrbmunjsinjuaewnmg"

[functions.sync-stripe-products]
verify_jwt = false

[functions.create-customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false